### ISSUE TITLE
Intel Windows unit tests

### ISSUE THREAD

**Issue by scivision** [gemini3d/gemini#7]
test_potential2d: will segfault without traceback, even in debug, on elliptic2d_cart call.

However, ifort windows is capable of running the main 4 tests (2d/3d, fang/glow).

**Comment by mattzett** [comment]
None of the four main unit tests actually use the solver that fails the unit test here, so that explains why they work fine.  The GDI and KHI examples do use this solver, so perhaps we should try them but I doubt they will pass if the unit test seg faults.  I don't have an intel setup right now so I can't really comment further until I get that going.

**Comment by scivision** [comment]
It's possible that 1df412f14af826755b might have fixed this. I didn't try it yet with Intel. This commit fixes GCC 10 warnings by using `allocate` instead of static declaration of large arrays.
